kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: k8dash
  namespace: kube-system
spec:
  rules:
    - host: k8dash.miaotai.com
      http:
        paths:
          - path: /
            backend:
              serviceName: k8dash
              servicePort: 80
